build: binaries for IBM Z (s390x) architecture (#228)
* Build binaries for IBM Z (s390x) architecture

* No separate linting on s390x architecture required

* newline

Co-authored-by: Alex Osadchyy <alex.osadchyy@ibm.com>
Co-authored-by: Alex Lewitt <48691328+alewitt2@users.noreply.github.com>

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -76,6 +76,39 @@ jobs:
            tags: true
            condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
 
+   - name: building s390x image
+     arch: s390x
+     script:
+       # Audit npm packages. Fail build whan a PR audit fails, otherwise report the vulnerability and proceed.
+       - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npm audit; else npm audit || true; fi
+       - npm test
+       - if [[ "${TRAVIS_TAG}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then npm version --no-git-tag-version "${TRAVIS_TAG}"; fi
+       - docker build --rm -t "quay.io/razee/watch-keeper:${TRAVIS_COMMIT}-s390x" .
+       - if [ -n "${TRAVIS_TAG}" ]; then docker tag quay.io/razee/watch-keeper:${TRAVIS_COMMIT}-s390x quay.io/razee/watch-keeper:${TRAVIS_TAG}-s390x; fi
+       - docker images
+       - ./build/process-template.sh kubernetes/watch-keeper/resource.yaml >/tmp/resource.yaml
+       - ./build/process-template.sh kubernetes/watch-keeper/rbac.yaml >/tmp/rbac.yaml
+       
+     before_deploy:
+       - docker login -u="${QUAY_ID}" -p="${QUAY_TOKEN}" quay.io
+       
+     deploy:
+       # Deploy alpha builds
+       - provider: script
+         script: docker push "quay.io/razee/watch-keeper:${TRAVIS_TAG}-s390x"
+         skip_cleanup: true
+         on:
+           tags: true
+           condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+_[0-9]{3}$
+
+       # Deploy released builds
+       - provider: script
+         script: docker push "quay.io/razee/watch-keeper:${TRAVIS_TAG}-s390x"
+         skip_cleanup: true
+         on:
+           tags: true
+           condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
+
    - stage: publish multi-arch image, npm & github release
      arch: amd64
      script:
@@ -84,7 +117,13 @@ jobs:
        - ./build/process-template.sh kubernetes/watch-keeper/rbac.yaml >/tmp/rbac.yaml
        - export DOCKER_CLI_EXPERIMENTAL=enabled 
        - sudo chown -R $USER:$USER /etc/docker/ 
-       - if [ -n "${TRAVIS_TAG}" ]; then docker manifest create quay.io/razee/watch-keeper:${TRAVIS_TAG} quay.io/razee/watch-keeper:${TRAVIS_TAG}-amd64 quay.io/razee/watch-keeper:${TRAVIS_TAG}-ppc64le; fi
+       - |
+         if [ -n "${TRAVIS_TAG}" ]; then
+            docker manifest create quay.io/razee/watch-keeper:${TRAVIS_TAG} \
+            quay.io/razee/watch-keeper:${TRAVIS_TAG}-amd64 \
+            quay.io/razee/watch-keeper:${TRAVIS_TAG}-ppc64le \
+            quay.io/razee/watch-keeper:${TRAVIS_TAG}-s390x
+         fi
        
      before_deploy:
        - docker login -u="${QUAY_ID}" -p="${QUAY_TOKEN}" quay.io
@@ -122,4 +161,4 @@ jobs:
          on:
            tags: true
            condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
-     
+
